# Devices:
# Syntax: %s %d:%d %s
# devices user:group mode

$MODALIAS=.*	0:0	0660	@modprobe -q -b "$MODALIAS"

# Set up /dev/disk/by-* symlinks
dasd.*		0:0 0660 */lib/mdev/persistent-storage
mmcblk.*	0:0 0660 */lib/mdev/persistent-storage
nbd.*		0:0 0660 */lib/mdev/persistent-storage
nvme.*		0:0 0660 */lib/mdev/persistent-storage
sd[a-z].*	0:0 0660 */lib/mdev/persistent-storage
sr[0-9]+	0:0 0660 */lib/mdev/persistent-storage
vd[a-z].*	0:0 0660 */lib/mdev/persistent-storage
xvd[a-z].*	0:0 0660 */lib/mdev/persistent-storage

md[0-9]		0:0 0660
