FROM codeberg.org/xens/x-mediawiki-php AS bld

ENV COMPOSER_ALLOW_SUPERUSER=1
RUN set -eux; apk add --no-cache bash git
RUN set -eux; \
	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"; \
	php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"; \
	php composer-setup.php; \
	php -r "unlink('composer-setup.php');";

ADD mw /mw
ADD scripts/strip-for-build.sh /

WORKDIR /mw
RUN set -eux; \
	php /opt/mediawiki/composer.phar install --no-dev --ignore-platform-reqs; \
	/strip-for-build.sh;

FROM scratch
COPY --from=bld /mw /
