FROM codeberg.org/xens/x-mediawiki-php AS bld

ENV COMPOSER_ALLOW_SUPERUSER=1
RUN set -eux; \
	apk add --no-cache bash git; \
	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"; \
	php -r "if (hash_file('sha384', 'composer-setup.php') === 'c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"; \
	php composer-setup.php; \
	php -r "unlink('composer-setup.php');";

ADD mw /mw
ADD scripts/strip-for-build.sh /

WORKDIR /mw
RUN set -eux; \
	php /opt/mediawiki/composer.phar install --no-dev; \
	/strip-for-build.sh;

FROM scratch
COPY --from=bld /mw /
