baseURL = 'https://blog.xtexx.eu.org/'
title = "xtex's Blog"
theme = 'arc'
copyright = 'Creative Commons Attribution-ShareAlike 4.0 International License'
enableRobotsTXT = true
enableGitInfo = true
hasCJKLanguage = true
rssLimit = 30
timeZone = "Asia/Shanghai"
buildDrafts = true
defaultContentLanguage = 'zh'
printPathWarnings = true

[params]
description = "xtex's Random Writings"
index_list = false

[params.author]
name = 'xtex'

[[params.links]]
text = "index"
url = "/"

[[params.links]]
text = "posts"
url = "/post"

[[params.links]]
text = "feed"
url = "/post/index.xml"

[[params.links]]
text = "home"
url = "https://xtexx.eu.org/"
target = "_blank"

[params.icon]
type = "image/png"
url = "/icon.png"

[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[permalinks]
post = '/:year/:month-:slugorcontentbasename'

[minify]
minifyOutput = true

[pagination]
pagerSize = 30

[languages]
[languages.zh]
locale = 'zh-hans'
direction = 'ltr'
label = 'Simplified Chinese'
weight = 1

[caches]
[caches.getresource]
dir = ':resourceDir/_cache'
maxAge = -1
[caches.misc]
dir = ':resourceDir/_cache'
maxAge = -1
