name = "xtex's MP Pack"
author = "xtex"
version = "2.15.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "627ff11d8e795fc10a4e898c58eb7f36460dabde4023f1827658f8d0e4a4ec65"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.5", "1.21.4", "1.21.3"]
