name = "xtex's MP Pack"
author = "xtex"
version = "2.15.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da48cbb3fc0df3e31644c72b103c6b03be99130cc7ed7791e673b5933f719071"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.5", "1.21.4", "1.21.3"]
