#:schema https://vide.pascal-lab.net/schemas/v1/vide.schema.json
sources = ["rtl/**", "vendor/taxi/src/axi/rtl/*", "vendor/common_cells/src/*"]

include_dirs = [
  "rtl",
  "rtl/utils",
  "rtl/interface",

  "rtl/mem",
  "rtl/frontend",

  "vendor/taxi/src/axi/rtl",
  "vendor/common_cells/src",
  "vendor/common_cells/include",
]
defines = ["SIMULATION"]
top_modules = ["top"]
libraries = ["vendor/taxi/src/axi/rtl", "vendor/common_cells/src"]
# exclude = ["build/**"]
