[group('gatus'), doc('Deploy Gatus configuration')]
gatus-deploy: (infra-sync "psf")

[group('gatus'), doc('Deploy Gatus container')]
gatus-deploy-container: (infra-sync "psf")
	./tiang -o psf -c 'cp ~/infra/gatus/gatus.container ~/.config/containers/systemd/gatus.container; \
		systemctl --user daemon-reload; \
		systemctl --user restart gatus.service'
