[group('gatus'), doc('Deploy Gatus configuration')]
gatus-deploy: (infra-sync "psf")

[group('gatus'), doc('Deploy Gatus container')]
gatus-deploy-container: (infra-sync "psf")
	./tiang -o psf -c '\
		mkdir -p ~/apps/gatus;\
		cp ~/infra/gatus/gatus.container ~/.config/containers/systemd/gatus.container; \
		systemctl --user daemon-reload; \
		systemctl --user restart gatus.service;\
		'

[group('gatus'), doc('Deploy Gatus local.yaml')]
gatus-deploy-local: (infra-sync "psf")
	./tiang -o psf \
		-t ./gatus/config/local.yaml /home/xtex/infra/gatus/config/local.yaml
