import 'psf.just'

[private]
infra-push:
	git diff --quiet main origin/main || git push

infra-sync host: infra-push
	./tiang -o '{{host}}' -infra pull

infra-sync-all: infra-push
	./tiang -infra pull

[private]
sd-user-daemon-reload host:
	./tiang -o '{{host}}' -c 'systemctl --user daemon-reload'

[private]
sd-user-restart host service:
	./tiang -o '{{host}}' -c 'systemctl --user restart {{service}}'

[private]
sd-user-reload host service:
	./tiang -o '{{host}}' -c 'systemctl --user reload {{service}}'
