FROM docker.io/library/alpine AS builder
ARG VERSION

RUN apk add build-base clang libcap meson git wget tar xz
RUN apk add libtool readline-dev libidn2-dev libuv-dev \
	nghttp2-dev libcap-dev jemalloc-dev json-c-dev openssl-dev>3 userspace-rcu-dev \
	krb5-dev json-c-dev libxml2-dev zlib-dev libidn2-dev
ADD https://ftp.isc.org/isc/bind9/$VERSION/bind-$VERSION.tar.xz /source.tar.xz
RUN tar -xf source.tar.xz
RUN mv bind-$VERSION src

WORKDIR /src
RUN set -euo pipefail; \
	export CC=clang CC_LD=lld CFLAGS='-O3' LDFLAGS='-flto'; \
	meson setup build-dir \
		--prefix=/usr/local --sysconfdir=/etc/bind --localstatedir=/var \
		-Dnamed-lto=full \
		-Ddoc=disabled \
		-Ddoh=enabled \
		-Didn=enabled \
		-Dstats-json=enabled \
		-Dstats-xml=enabled \
		-Dzlib=enabled \
		-Djemalloc=enabled \
		-Dgssapi=enabled \
		; \
	meson compile -C build-dir; \
	meson install -C build-dir; \
	rm -rf /usr/local/{include,share/man};

FROM docker.io/library/alpine
RUN apk add libtool readline libidn2 libuv \
	nghttp2 json-c openssl>3 jemalloc \
	userspace-rcu krb5 libcap json-c libxml2 zlib libidn2
COPY --from=builder /usr/local /usr/local
RUN mkdir -p /etc/bind /var/run/bind
RUN /usr/local/sbin/named --help 

LABEL org.opencontainers.image.licenses="MPL-2.0"
LABEL org.opencontainers.image.source="https://codeberg.org/xens/atremis"
LABEL org.opencontainers.image.title="bind"
LABEL org.opencontainers.image.url="https://bind.isc.org/"
LABEL org.opencontainers.image.vendor="Xensor V Project"

WORKDIR /
EXPOSE 53/udp 53/tcp 953/tcp
CMD ["/usr/local/sbin/named", "-g", "-c", "/etc/bind/named.conf"]
