ARG VERSION
FROM docker.io/library/php:$VERSION-fpm-alpine

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN set -euxo pipefail; \
	apk add --no-cache \
		lighttpd \
		dinit \
		git \
		imagemagick \
		rsvg-convert \
		# Required for SyntaxHighlighting
		python3 \
		lua \
		diffutils; \
	install-php-extensions calendar intl mbstring opcache apcu pgsql mysqli luasandbox gd wikidiff2 openssl; \
	rm /usr/local/bin/install-php-extensions; \
	{ \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=60'; \
	} > $PHP_INI_DIR/conf.d/opcache-recommended.ini; \
	mkdir -p /var/www/data; \
	true;

ADD php-fpm.conf /usr/local/etc/php-fpm.d/zzzz-mw-docker.conf
ADD php.ini $PHP_INI_DIR/conf.d/mw.ini
ADD dinit.d /etc/dinit.d

ENV MW_CONFIG_FILE=/etc/mediawiki/LocalSettings.php
WORKDIR /opt/mediawiki

ENTRYPOINT [ "/usr/bin/dinit", "-s" ]

LABEL org.opencontainers.image.licenses="PHP-3.01"
LABEL org.opencontainers.image.source="https://codeberg.org/xens/atremis"
LABEL org.opencontainers.image.title="MediaWiki-PHP"
LABEL org.opencontainers.image.url="https://www.php.net/"
LABEL org.opencontainers.image.vendor="Xensor V Project"
