FROM docker.io/library/alpine AS builder
ARG VERSION

RUN apk add build-base clang libcap git autoconf
RUN apk add flex-dev bison m4 libssh-dev linux-headers ncurses-dev readline-dev bash

ADD https://gitlab.nic.cz/labs/bird/-/archive/v$VERSION/bird-v$VERSION.tar.gz /source.tar.gz
RUN tar -xf source.tar.gz
RUN mv bird-v$VERSION src

WORKDIR /src
RUN set -euxo pipefail; \
	autoreconf; ./configure CC=clang CFLAGS='-O3' LDFLAGS='-flto' \
		--prefix=/usr/local --sysconfdir=/etc/bird --runstatedir=/var/run/bird \
		--enable-client \
		--enable-pthreads \
		--enable-libssh \
		--enable-mpls-kernel \
		--with-protocols=all; \
	make -j$(nproc) && make install; \
	setcap CAP_NET_ADMIN=+eip /usr/local/sbin/bird

FROM docker.io/library/alpine
RUN apk add libssh ncurses readline
COPY --from=builder /etc/bird /etc/bird
COPY --from=builder /usr/local /usr/local
RUN mkdir -p /var/run/bird

WORKDIR /
ENTRYPOINT [ "/usr/local/sbin/bird", "-f" ]

LABEL org.opencontainers.image.licenses="GPL-2.0-or-later"
LABEL org.opencontainers.image.source="https://codeberg.org/xens/atremis"
LABEL org.opencontainers.image.title="BIRD"
LABEL org.opencontainers.image.url="https://bird.network.cz/"
LABEL org.opencontainers.image.vendor="Xensor V Project"
