preset-xtex-alerts: &alerts
  alerts:
    - type: discord

preset-xtex-domains: &domains
  group: 01-domains
  interval: 1h
  conditions:
    - "[DOMAIN_EXPIRATION] > 720h"
  <<: *alerts

endpoints:
  - name: "xtex's Home"
    group: 00-sites
    url: "https://xtexx.eu.org/nodeinfo/2.1.json"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].software.name == xtex-home"
      - "[CERTIFICATE_EXPIRATION] > 72h"
    <<: *alerts
  - name: "xtex's Blog"
    group: 00-sites
    url: "https://blog.xtexx.eu.org/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 72h"
    <<: *alerts
  - name: "xtex's Uptime"
    group: 00-sites
    url: "https://uptime.xtexx.eu.org/health"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"
      - "[CERTIFICATE_EXPIRATION] > 72h"
    <<: *alerts
  - name: "xtex's Upptime"
    group: 00-sites
    url: "https://upptime.xtexx.eu.org/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 72h"
    <<: *alerts
  # - name: xtexx.eu.org
  #   <<: *domains
  #   url: "https://xtexx.eu.org"
  # - name: xtexx.us.kg
  #   <<: *domains
  #   url: "https://xtexx.us.kg"
  - name: hgdns.ren
    <<: *domains
    group: 03-flcc
    url: "https://hgdns.ren"
  - name: "yjyz-tools"
    group: 03-yjyz-tools
    url: "https://yjyz.us.kg/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 72h"
    <<: *alerts
  # - name: yjyz.us.kg
  #   <<: *domains
  #   group: yjyz-tools
  #   url: "https://yjyz.us.kg"
