endpoints:
  - name: "xtex's Home"
    group: xtex
    url: "https://xtexx.eu.org/nodeinfo/2.1.json"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].software.name == xtex-home"
      - "[CERTIFICATE_EXPIRATION] > 72h"
  - name: "xtex's Blog"
    group: xtex
    url: "https://blog.xtexx.eu.org/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 72h"
  - name: "xtex's Uptime"
    group: xtex
    url: "https://uptime.xtexx.eu.org/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 72h"
  - name: "xtex's Upptime"
    group: xtex
    url: "https://upptime.xtexx.eu.org/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 72h"
