endpoints:
  - name: "Xensor V Network IdM"
    group: xvnet
    url: "https://id.xvnet.eu.org/auth/v1/health"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].db_healthy == true"
      - "[BODY].cache_healthy == true"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: "Xensor V Wiki"
    group: xvnet
    url: "https://w.xvnet.eu.org"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: "Xens Meta Wiki"
    group: xvnet
    url: "https://meta.w.xvnet.eu.org"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: "FLCC Wiki"
    group: xvnet
    url: "https://hgdns.ren"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: "Xensor V Ntfy"
    group: xvnet
    url: "https://ntfy.xvnet.eu.org/v1/health"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].healthy == true"
      - "[CERTIFICATE_EXPIRATION] > 48h"
