preset-domains: &domains
  group: xvnet-domain
  interval: 1h
  conditions:
    - "[DOMAIN_EXPIRATION] > 720h"

endpoints:
  - name: "Xensor V Network IdM"
    group: xvnet-service
    url: "https://id.xvnet.eu.org/auth/v1/health"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].db_healthy == true"
      - "[BODY].cache_healthy == true"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: "Xensor V Ntfy"
    group: xvnet-service
    url: "https://ntfy.xvnet.eu.org/v1/health"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].healthy == true"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: "Xensor V Wiki"
    group: xvnet-wiki
    url: "https://w.xvnet.eu.org"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: "Xens Meta Wiki"
    group: xvnet-wiki
    url: "https://meta.w.xvnet.eu.org"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: "FLCC Wiki"
    group: xvnet-wiki
    url: "https://hgdns.ren"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: "xvnet.eu.org"
    <<: *domains
    url: "https://xvnet.eu.org"
  - name: "xvnet0.eu.org"
    <<: *domains
    url: "https://xvnet0.eu.org"
  - name: "xvnet.net.eu.org"
    <<: *domains
    url: "https://xvnet.net.eu.org"
