# XV-NET Generated BIRD Configuration for <% $HOSTNAME %>

log stderr all;
router id <% $BIRD_ROUTER_ID %>;
define DN42_LOCAL_IP = <% $DN42_LOCAL_IP %>;
define XVNET_ASN = <% $XVNET_ASN %>;
define XVNET_LOCAL_IP = <% $XVNET_LOCAL_IP %>;

protocol device {}

protocol direct {
	ipv4;
	ipv6;
	interface
		"-podman*", # exclude Podman interfaces
		"-veth*", # exclude container interfaces
		"*";
}

.INCLUDE services/bird/conf/bogon.conf
.INCLUDE services/bird/conf/xvnet.conf
.INCLUDE services/bird/conf/dn42.conf

protocol kernel kernel4 {
	ipv4 {
		import none;
		export filter {
			if is_dn42_prefix() then krt_prefsrc = DN42_LOCAL_IP;
			accept;
		};
	};
};

protocol kernel kernel6 {
	ipv6 {
		import none;
		export filter {
			if is_xvnet_prefix() then krt_prefsrc = XVNET_LOCAL_IP;
			else if is_dn42_prefix() then krt_prefsrc = XVNET_LOCAL_IP;
			accept;
		};
	};
};

.INCLUDE services/bird/conf/xvnet_template.conf
.INCLUDE services/bird/conf/dn42_template.conf

include "/etc/bird/peers.conf";
