filter dn42_import {
	if ! is_dn42_prefix() then {
		reject "[dn42] reject non-DN42 route: ", net, ", ", bgp_path.last, ", ", proto;
	}
	if is_xvnet_prefix() then reject;
	if bgp_path.len > 10 then {
		reject; # "[dn42] reject too long path ", net, ", ", bgp_path.len, " AS on path, ", proto, ", ", bgp_path;
	}
	if check_dn42_roa() != ROA_VALID then {
		reject; # "[dn42] ROA failed for ", net, " ASN ", bgp_path.last, ", ", proto;
	}
	if check_dn42_roa_flap() then {
		reject; # "[dn42] reject flapping route: ", net, ", ", bgp_path.last, ", ", proto;
	}
	if bgp_community ~ COMMUNITY_DN42_UNSAFE then bgp_large_community.add(COMMUNITY_XVN_UNSAFE_TRANSIT);

	if COMMUNITY_XVN_UNSAFE_TRANSIT ~ bgp_large_community then bgp_local_pref = bgp_local_pref - 20;

	bgp_local_pref = bgp_local_pref - (bgp_path.len * 2);
	accept;
}

filter dn42_export {
	if !is_dn42_prefix() then reject;
	if is_xvnet_prefix() && !is_dn42_export_prefix() then reject;
	if COMMUNITY_XVN_NO_TRANSIT ~ bgp_large_community then reject;

	strip_confed_as();
	if COMMUNITY_XVN_UNSAFE_TRANSIT ~ bgp_large_community
		then bgp_community.add((64511, 32));
		else bgp_community.add((64511, 34));
	bgp_large_community.add(COMMUNITY_XVN_EXPORT_SELF);
	accept;
}

template bgp dn42_peer {
	local as 4242420361;
	graceful restart on;
	enable extended messages on;
	advertise hostname on;

	ipv4 {
		import filter dn42_import;
		export filter dn42_export;
		import limit 2000 action block;
		export limit 2000 action disable;
		extended next hop on;
	};

	ipv6 {
		import filter dn42_import;
		export filter dn42_export;
		import limit 2000 action block;
		export limit 2000 action disable;
		extended next hop on;
	};
}

protocol bgp dn42_grc from dn42_peer {
	neighbor fd42:d42:d42:179::1 as 4242422602;
	multihop;
	ipv4 {
		add paths tx;
		import none;
		export limit off;
	};
	ipv6 {
		add paths tx;
		import none;
		export limit off;
	};
};

protocol rpki dn42_roa_strexp {
    roa4 { table dn42_roa_flap4; };
    roa6 { table dn42_roa_flap6; };

    remote "rpki.nia.dn42" port 8083;
	local address XVNET_LOCAL_IP;

    retry keep 120;
    refresh keep 300;
    expire keep 600;
}
