filter afnet_import {
	if (!is_xvnet_prefix()) && (!is_dn42_prefix()) then {
		reject "[afnet] reject invalid route: ", net, ", ", bgp_path.last, ", ", proto;
	}
	if bgp_path.len > 10 then {
		reject "[afnet] reject too long path ", net, ", ", bgp_path.len, " AS on path, ", proto, ", ", bgp_path;
	}

	if COMMUNITY_XVN_UNSAFE_TRANSIT ~ bgp_large_community then bgp_local_pref = bgp_local_pref - 20;

	# opilio to strexp
	if bgp_path.first = 4244310001 && bgp_path.last = 4242421331 then bgp_local_pref = bgp_local_pref + 30;

	bgp_local_pref = bgp_local_pref - (bgp_path.len * 2);
	accept;
}

filter afnet_import_notransit {
	if (!is_xvnet_prefix()) && (!is_dn42_prefix()) then {
		reject "[afnet] reject invalid route: ", net, ", ", bgp_path.last, ", ", proto;
	}
	if bgp_path.len > 10 then {
		reject "[afnet] reject too long path ", net, ", ", bgp_path.len, " AS on path, ", proto, ", ", bgp_path;
	}

	if COMMUNITY_XVN_UNSAFE_TRANSIT ~ bgp_large_community then bgp_local_pref = bgp_local_pref - 20;

	# opilio to strexp
	if bgp_path.first = 4244310001 && bgp_path.last = 4242421331 then bgp_local_pref = bgp_local_pref + 30;

	bgp_large_community.add(COMMUNITY_XVN_NO_TRANSIT);
	bgp_local_pref = bgp_local_pref - (bgp_path.len * 2) - 1;
	accept;
}

filter afnet_export {
	if (!is_xvnet_prefix()) && (!is_dn42_prefix()) then reject;
	if bgp_path.len > 7 then reject;
	accept;
}

template bgp afnet_peer {
	local as XVNET_ASN;
	graceful restart on;
	enable extended messages on;
	advertise hostname on;

	ipv4 {
		import filter afnet_import;
		export filter afnet_export;
		import limit 2000 action block;
		export limit 2000 action disable;
		extended next hop on;
	};

	ipv6 {
		import filter afnet_import;
		export filter afnet_export;
		import limit 2000 action block;
		export limit 2000 action disable;
		extended next hop on;
	};
}

template bgp afnet_peer_notransit {
	local as XVNET_ASN;
	graceful restart on;
	enable extended messages on;
	advertise hostname on;

	ipv4 {
		import filter afnet_import_notransit;
		export filter afnet_export;
		import limit 2000 action block;
		export limit 2000 action disable;
		extended next hop on;
	};

	ipv6 {
		import filter afnet_import_notransit;
		export filter afnet_export;
		import limit 2000 action block;
		export limit 2000 action disable;
		extended next hop on;
	};
}
