# XV-NET filters

define COMMUNITY_XVN_OPTS						= [ (4244310000, 0, *) ];
define COMMUNITY_XVN_NO_TRANSIT					= (4244310000, 0, 1);
define COMMUNITY_XVN_UNSAFE_TRANSIT				= (4244310000, 0, 2);

define COMMUNITY_XVN_EXPORT_NODE				= [ (4244310000, 2, *) ];
define COMMUNITY_XVN_EXPORT_SELF				= (4244310000, 2, <% $XVNET_NUM %>);

define COMMUNITY_BLACKHOLE						= (65535, 666);

% xvnetPrefixesV4=('172.20.206.64/27+')
% xvnetPrefixesV6=('fd00:443a:ef14::/48+')

define XVNET_PREFIXES_V4 = [ <%% IFS=','; echo "${xvnetPrefixesV4[*]}" %> ];
define XVNET_PREFIXES_V6 = [ <%% IFS=','; echo "${xvnetPrefixesV6[*]}" %> ];

function is_xvnet_prefix() -> bool {
	case net.type {
		NET_IP4: return net ~ XVNET_PREFIXES_V4;
		NET_IP6: return net ~ XVNET_PREFIXES_V6;
		else: print "is_xvnet_prefix: unexpected net.type ", net.type, " ", net; return false;
	}
}

protocol static static6 {
	route fd00:443a:ef14::/48 reject;

	ipv6 {
		import all;
		export none;
	};
}

function strip_confed_as() {
	bgp_path.delete([4244310000..4244319999]);
}
