FROM docker.io/library/alpine AS bld
ARG VERSION

# FIXME https://github.com/mariadb-corporation/wsrep-lib/pull/257/changes \
RUN set -eux; \
	apk add \
		build-base ninja cmake git \
		clang lld \
		zlib-dev ncurses-dev libaio-dev jemalloc-dev \
		snappy-dev gnutls-dev libevent-dev bison gzip \
		libxml2-dev boost-dev lz4-dev bzip2-dev lzo-dev curl-dev \
	; \
	git clone --depth 1 --recurse-submodules --shallow-submodules -b $VERSION https://github.com/MariaDB/server.git bld; \
	cd bld; \
	( \
		echo '#include <cstdint>'; \
		cat wsrep-lib/include/wsrep/provider_options.hpp; \
	) | tee wsrep-lib/include/wsrep/provider_options.hpp1; \
	mv wsrep-lib/include/wsrep/provider_options.hpp1 wsrep-lib/include/wsrep/provider_options.hpp; \
	mkdir build; cd build; \
	CXX=clang++ CC=clang LD=ld.lld \
	cmake -E time cmake .. \
		-G Ninja \
		-DBUILD_CONFIG=mysql_release \
		-DPLUGIN_FEEDBACK=NO \
		-DPLUGIN_AUTH_PAM=NO \
		-DPLUGIN_AUTH_GSSAPI=NO \
		-DPLUGIN_AUTH_GSSAPI_CLIENT=OFF \
		-DPLUGIN_AUTH_SOCKET=YES \
		-DPLUGIN_S2=NO \
		-DPLUGIN_ROCKSDB=NO \
		-DPLUGIN_CONNECT=NO \
		-DPLUGIN_SPHINX=NO \
		-DPLUGIN_TOKUDB=NO \
		-DPLUGIN_CRACKLIB_PASSWORD_CHECK=NO \
		-DWITH_SSL=yes \
		-DWITH_JEMALLOC=ON \
		-DWITH_ZLIB=ON \
		-DSKIP_TESTS=ON \
		; \
	cmake -E time cmake --build . -j $(nproc); \
	cmake -E time cmake --install .;

FROM docker.io/library/alpine

COPY --from=bld /usr/local /usr/local
RUN set -eux; \
	rm -rf /usr/local/man /usr/local/sql-bench /usr/local/mariadb-test; \
	apk add --no-cache \
		libaio libstdc++ libgcc \
		ncurses zlib gnutls bison gzip \
		libxml2 lz4 bzip2 lzo \
		; \
	mkdir -p /var/lib/mariadb

ENV MARIADB_HOME=/var/lib/mariadb
WORKDIR /var/lib/mariadb
ENTRYPOINT [ "/usr/local/mysql/bin/mariadbd" ]

LABEL org.opencontainers.image.licenses="GPL-2.0-or-later"
LABEL org.opencontainers.image.source="https://codeberg.org/xens/atremis"
LABEL org.opencontainers.image.title="MariaDB"
LABEL org.opencontainers.image.url="https://mariadb.com/"
LABEL org.opencontainers.image.vendor="Xensor V Project"
