//! Example usage:
//! git clone https://github.com/loongson-community/loongarch-opcodes.git ../loongarch-opcodes
//! zig run tools/gen_decode_tree.zig -- ../loongarch-opcodes .
//!
//! Modified from ziglang/zig tools/gen_loongarch_encoding.zig.
//! OpcodeDesc.zig and decode_tree.zig are also from ziglang.

const std = @import("std");
const fs = std.fs;
const Allocator = std.mem.Allocator;
const print = std.debug.print;
const Writer = std.Io.Writer;
const ZonSerializer = std.zon.Serializer;

const OpcodeDesc = @import("OpcodeDesc.zig");
const decode_tree = @import("decode_tree.zig");

const desc_files: []const []const u8 = &.{
    "la-base-32.txt",
    "la-base-64.txt",
    "la-bitops-32.txt",
    "la-bitops-64.txt",
    "la-atomics-32.txt",
    "la-atomics-64.txt",
    "la-bound.txt",
    "la-bound-64.txt",
    "la-mul-32.txt",
    "la-mul-64.txt",
    "la-privileged-32.txt",
    "la-privileged-64.txt",
};

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;

    var args = try init.minimal.args.iterateAllocator(arena);
    const arg0 = args.next().?;
    const opcodes_path = args.next() orelse usageAndExit(arg0, 0);
    const zig_path = args.next() orelse usageAndExit(arg0, 1);
    args.deinit();

    var desc: OpcodeDesc = .{};
    defer desc.deinit(arena);

    var src_dir = try std.Io.Dir.cwd().openDir(io, zig_path, .{});
    defer src_dir.close(io);

    // load opcode data
    {
        print("Loading description files ..\n", .{});
        var opcodes_dir = try std.Io.Dir.cwd().openDir(io, opcodes_path, .{ .iterate = true });
        defer opcodes_dir.close(io);

        for (desc_files) |file_name| {
            print("Loading {s} ...\n", .{file_name});
            const data = try opcodes_dir.readFileAlloc(io, file_name, arena, .unlimited);
            try desc.parse(arena, data);
            // `data` is intentionally leaked here because it must live longer than `desc`
            // ArenaAllocator should clean them up.
        }

        print("Loading extra.txt ...\n", .{});
        const data = try src_dir.readFileAlloc(io, "tools/extra.txt", arena, .unlimited);
        try desc.parse(arena, data);

        print("Loaded {} instructions, {} formats\n", .{ desc.opcode.items.len, desc.format.count() });
        desc.sort();
        print("Sorted data\n", .{});
    }

    // generate decode_tree.svh
    {
        print("Writing decode_tree.svh ...\n", .{});
        var buffer: Writer.Allocating = .init(arena);
        defer buffer.deinit();
        const writer = &buffer.writer;

        try writer.print(
            \\// DO NOT MODIFY. This file is generated by tools/gen_decode_tree.zig.
            \\
            \\`define LA_DECODE_TREE \
            \\
        , .{});

        try printDecodeTree(writer, arena, &desc);

        try src_dir.writeFile(io, .{
            .sub_path = "rtl/gen/decode_tree.svh",
            .data = buffer.written(),
        });
    }

    print("Done.\n", .{});
}

fn usageAndExit(arg0: []const u8, code: u8) noreturn {
    print(
        \\Usage: {s} /path/loongarch-opcodes /path/zig
        \\
        \\Updates LoongArch decode tree from loongarch-opcodes.git.
        \\
    , .{arg0});
    std.process.exit(code);
}

fn printDecodeTree(writer: *Writer, gpa: Allocator, desc: *const OpcodeDesc) !void {
    var arena: std.heap.ArenaAllocator = .init(gpa);
    defer arena.deinit();
    const root_node = try decode_tree.populate(arena.allocator(), desc);
    try printIndentation(writer, 1);
    try printDecodeTreeNode(writer, root_node, 1);

    try writer.writeAll("\n");
    for (desc.opcode.items) |*opcode| {
        try writer.print(
            \\
            \\`ifndef LA_DECODE_INST_{s}
            \\`ifdef SYNTHESIS
            \\`define LA_DECODE_INST_{s} invalid_inst = 1;
            \\`else
            \\`define LA_DECODE_INST_{s} \
            \\  begin \
            \\    if (!rst) $warning("Unimplemented opcode {s}"); \
            \\    invalid_inst = 1; \
            \\  end
            \\`endif
            \\`endif
            \\
        , .{ opcode.sv_name, opcode.sv_name, opcode.sv_name, opcode.orig_name });
    }
}

fn printDecodeTreeNode(writer: *Writer, node: *const decode_tree.Node, indent: usize) !void {
    if (node.mask == 0) {
        try writer.print("`LA_DECODE_INST_{s}", .{node.next.instruction.sv_name});
    } else {
        try writer.print("unique case (in.inst & 32'h{x:0>8}) \\\n", .{node.mask});
        var caught_all = false;
        for (node.next.cases) |*case| {
            try printIndentation(writer, indent + 1);
            if (case.catch_all) {
                caught_all = true;
                try writer.print("default: ", .{});
            } else {
                try writer.print("32'h{x:0>8}: ", .{case.variant});
            }
            try printDecodeTreeNode(writer, case.child, indent + 1);
            try writer.print(" \\\n", .{});
        }
        if (!caught_all) {
            try printIndentation(writer, indent + 1);
            try writer.print("default: invalid_inst = 1; \\\n", .{});
        }
        try printIndentation(writer, indent);
        try writer.print("endcase", .{});
    }
}

fn printIndentation(writer: *Writer, indent: usize) !void {
    try writer.splatByteAll(' ', 2 * indent);
}
